Fix/get cities from state
penguinuux/rain-forecast-risk-alert pull request #42
Opened 2022-05-05 23:26 UTC by JOSUE-ASV

fix: normalization of fetched values and returns cities in string list format

2022-05-05 23:29 UTC, marcelosj3 requested changes

2022-05-05 23:29 UTC, marcelosj3 commented on app/services/cities_services.py
> +        for estate in states
Typo, should be **state** instead of estate.

2022-05-05 23:29 UTC, marcelosj3 commented on app/services/cities_services.py
> +    city_state = [
Since this is a state dict with a list of cities, the name could be state_and_cities, or something like this.

2022-05-05 23:55 UTC, penguinuux approved these changes

2022-05-06 00:32 UTC, marcelosj3 requested changes

2022-05-06 00:32 UTC, marcelosj3 commented on app/services/cities_services.py
> +        for estate in states
Typo, should be **state** instead of estate.

2022-05-06 00:40 UTC, marcelosj3 approved these changes

2022-05-06 00:41 UTC, merged