feature/forecast-risk
penguinuux/rain-forecast-risk-alert pull request #9
Opened 2022-04-30 22:22 UTC by marcelosj3

Created a forecast risk route along with the necessary validations, also created some new folders and files.

2022-04-30 22:57 UTC, marcelosj3 commented on README.md
> +```json
I've added a body in the errors, but if someone think this is not necessary i can delete it.

2022-05-01 20:04 UTC, penguinuux requested changes

2022-05-01 20:04 UTC, penguinuux commented on README.md
>  | Nome       | Descrição                                         |
Must be translated to english.

2022-05-01 21:50 UTC, luizpcardoso approved these changes

2022-05-01 21:59 UTC, marcelosj3 commented on README.md
>  | Nome       | Descrição                                         |
Done.

2022-05-01 22:00 UTC, penguinuux approved these changes

2022-05-01 22:00 UTC, merged